spring.application.name=BankingManagement
server.port=4899

#spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/employee_leave
spring.datasource.username=root
spring.datasource.password=Lipu@9938
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/priyabratrealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/priyabratrealm/protocol/openid-connect/certs

# JWT Configuration
jwt.auth.converter.resource-id=mynewclient
jwt.auth.converter.principal-attribute=priyadev

# Logging Configuration
logging.level.org.springframework.security=DEBUG

# keycloack url
key.cloak.token.token.url=http://localhost:8080/realms/priyabratrealm/protocol/openid-connect/token
